name: Audit

on:
  workflow_dispatch:
  schedule:
    - cron: "17 11 * * 1"
  push:
    paths:
      - Cargo.lock
      - Cargo.toml
      - .github/workflows/audit.yml
  pull_request:
    paths:
      - Cargo.lock
      - Cargo.toml
      - .github/workflows/audit.yml

permissions:
  contents: read

concurrency:
  group: audit-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      RUSTUP_TOOLCHAIN: stable
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
        with:
          toolchain: stable
      - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
